TrueFiEng/useDApp

packages/core/.mocharc.json
packages/core/package.json
packages/core/test/blockNumber.test.tsx
packages/core/test/test.test.ts
packages/core/test/useBlockNumber.test.tsx
packages/core/test/utils/index.ts
packages/core/test/utils/testConnector.ts
packages/core/test/utils/waitUntil.ts
packages/core/test/utils/web3Wrapper.tsx
yarn.lock

First step of https://github.com/EthWorks/useDapp/issues/25

🧱 Add a high level test for useBlockNumber

---

packages/core/test/useBlockNumber.test.tsx
packages/core/test/utils/index.ts
packages/core/test/utils/mockConnector.ts
packages/core/test/utils/mockWeb3Wrapper.tsx
packages/core/test/utils/web3Wrapper.tsx

Minor proposals from comments in https://github.com/EthWorks/useDapp/pull/26

📛 Rename mock classes

---

.changeset/nine-pumas-think.md
docs/source/core.rst
packages/core/src/helpers/address.ts
packages/core/src/helpers/index.ts
packages/core/test/helpers/address.test.ts

🚁 Add address helpers

---

packages/core/package.json

ethereum-waffle is the dev only package, should put in devDependencies

move ethereum-waffle to devDependencies

---

.changeset/little-steaks-matter.md

😅 Add changesets

---

.changeset/strange-deers-deny.md
packages/core/src/constants/chainId.ts

Support a general chainId for all local nodes

add localhost to chainIds

---

.changeset/fair-actors-kneel.md
packages/example/webpack.config.js

Remove git version from webpack config

---

.changeset/gentle-starfishes-attack.md
packages/core/package.json
packages/core/tsconfig.json

On example page bundle size is around 100kb smaller with tree shaking.

Emit esm package

---

docs/source/conf.py
docs/source/core.rst
docs/source/guide.rst

Fix some docs typos and ref error

---

.changeset/tiny-teachers-approve.md
docs/source/core.rst
packages/core/src/constants/chainId.ts
packages/core/src/helpers/chain.ts
packages/core/src/model/config/default.ts
packages/core/test/helpers/chain.test.ts

Add BSC chain id, explorer
and the multicall contract on https://github.com/makerdao/multicall/pull/20/files
test, lint passed

Add BSC support

---

packages/example/README.md
packages/example/package.json

Right now, I have to run both:
```
yarn
yarn add @usedapp/core
```
in order for this to run. The `*` appears to be ignored. Also cleaned up the example readme.

example quality of life improvements

---

.changeset/green-scissors-promise.md
packages/example/src/components/Transactions/History.tsx
packages/example/src/components/account/AccountButton.tsx
packages/example/src/components/account/AccountModal.tsx
packages/example/src/global/styles.ts
packages/example/src/pages/Balance.tsx
packages/example/src/pages/SendEtherPage.tsx
packages/example/src/pages/Tokens.tsx
packages/example/src/pages/Transactions.tsx

Change transaction history to modal

---

.changeset/pink-geese-deny.md
packages/example/src/components/Transactions/History.tsx
packages/example/src/components/account/AccountButton.tsx
packages/example/src/global/styles.ts
packages/example/src/pages/SendEtherPage.tsx
packages/example/src/pages/Transactions.tsx

Change notifications to popups

---

.changeset/big-knives-explain.md
packages/core/src/providers/config/context.ts
packages/core/src/providers/config/provider.tsx
packages/core/src/providers/config/reducer.ts
packages/testing/examples/useConfig.test.tsx

This PR will add `useSetHook` that returns `setConfig` function.
Set config accepts object as parameter that will be used to update config.

Introduce useUpdateConfig

---

.changeset/red-balloons-sell.md
docs/source/core.rst
packages/core/src/constants/chainId.ts
packages/core/src/helpers/chain.ts
packages/core/src/model/config/default.ts
packages/core/test/helpers/chain.test.ts

Inspired from https://github.com/EthWorks/useDApp/commit/21f59f6f80bc9307abaa1dc3cb6e17230b77899f

Add Polygon and Mumbai support

---

.changeset/tough-ligers-hunt.md
docs/source/core.rst
packages/core/src/constants/chainId.ts
packages/core/src/helpers/chain.ts
packages/core/src/model/config/default.ts
packages/core/test/helpers/chain.test.ts

Adds support for the Harmony Blockchain - tests & linter passing.

Add Harmony support

---

.changeset/selfish-rings-act.md
package.json
packages/core/package.json
packages/testing/package.json
yarn.lock

Upgrading ethers.js to version 5.4.1 that implements EIP 1559

Upgrade to ethers.js to 5.4.1

---

.changeset/light-queens-appear.md
packages/core/src/hooks/usePromiseTransaction.ts

Use the full errors from RPC client if error object exists

feat: better error messaging [previous version got overwritten]

---

.changeset/eight-trees-provide.md
packages/core/src/constants/abi/ERC20.json

current useDApp ERC20.json doesn't include this method
use the ABI in https://ethereumdev.io/abi-for-erc20-contract-on-ethereum/
fix #295

fix: update ERC20 ABI

---

.changeset/moody-cycles-think.md
packages/core/package.json
packages/core/src/providers/config/reducer.ts
yarn.lock

Add missing lodash-merge dependency

---

.changeset/cold-pugs-greet.md
package.json
packages/core/package.json
packages/extension/package.json
packages/testing/package.json
yarn.lock

Bump ethers version

---

packages/extension/CHANGELOG.md

Linter is showing error in extension changelog. Fixed.

🔧 Fix change log linter

---

packages/core/src/hooks/useContractFunction.ts
packages/core/src/providers/chainState/callsReducer.ts
packages/core/src/providers/chainState/provider.tsx
packages/core/test/helpers/address.test.ts
packages/extension/src/providers/events/reducer/accountChanged.ts
packages/extension/src/providers/events/reducer/callsChanged.ts
packages/extension/src/providers/events/reducer/multicallSuccess.ts
packages/extension/src/views/NameTags/NameTags.tsx

https://github.com/EthWorks/useDApp/issues/363

feat: case insensitive address comparing

---

.changeset/short-bobcats-search.md
docs/source/core.rst
packages/core/src/model/config/Config.ts
packages/core/src/model/config/default.ts
packages/core/src/providers/DAppProvider.tsx
packages/core/src/providers/NetworkActivator.tsx

https://github.com/EthWorks/useDApp/issues/369

🔌 Enable configuring autoconnection to provider

---

packages/core/src/providers/transactions/model.ts

⁉️ getStoredTransactionState - transaction can't be undefined

---

.changeset/unlucky-kiwis-perform.md
packages/core/src/providers/config/reducer.ts

Fix can't resolve 'lodash/merge #432

---

.changeset/nine-queens-repair.md
docs/source/getting-started.rst

Fixed the chainId property name in the Getting Started

---

.changeset/purple-starfishes-melt.md
packages/core/src/model/chain/polygon.ts
packages/core/test/model/chain/polygon.test.ts

polygon's default explorer is changed to https://polygonscan.com/

🧐 Replace polygon explorer to polyscan

---

docs/source/core.rst
docs/source/guide.rst

Update activateBrowserWallet documentation

---

packages/docs/docs/alternative-getting-started.mdx

https://app.asana.com/0/1201906120944847/1201994471245191
https://github.com/paulrberg/create-eth-app

📜 Add documentation for create eth-app

---

packages/core/README.md

🏷 Add labels

---

.changeset/tender-cycles-divide.md
packages/core/src/helpers/calls.ts
packages/core/src/providers/chainState/multiChainStates/provider.tsx

getUniqueCalls took about a second for over 250 calls in TrueFi and was called unnecessary often

⛳️ Optimize getUniqueCalls usage

---

.changeset/quiet-laws-run.md
packages/core/src/providers/network/network/provider.tsx

https://github.com/TrueFiEng/useDApp/issues/576

🙊 Fix metamask auto-connection behaviour

---

.changeset/metamask-change-account-problem.md
packages/core/src/hooks/useEthers.ts

https://app.asana.com/0/1201906120944847/1202122776088472

🐯 Solve getting lowercase account number from metamask

---

packages/core/src/providers/LocalMulticallProvider.tsx

Deploy multicall2 on localhost if the version in config is multicall2

🧠 Deploy multicall2 on localhost

---

.changeset/yellow-seahorses-live.md
packages/core/src/hooks/useRawLogs.test.ts
packages/core/src/hooks/useRawLogs.ts

Adds a hook for retrieving contract event logs from the provider.
:heavy_check_mark: 5 tests added
:heavy_check_mark: All tests passing
:heavy_check_mark: Linter passing

🪵 Add useRawLogs hook

---

packages/docs/docs/03-API Reference/05-Helpers.mdx

Closes https://github.com/TrueFiEng/useDApp/issues/751

🎍 Add example to `getChainName` docs

---

.changeset/clever-jars-wait.md
packages/core/src/model/types.ts

- Change record value type to any instead of string

🐛 Fix EventRecord type issue

---

packages/core/src/helpers/getAddNetworkParams.ts

Closes https://github.com/TrueFiEng/useDApp/issues/763

🍞 Correct `nativeCurrency` in network params

---

.changeset/large-roses-sing.md
packages/core/src/hooks/useContractFunction.ts
packages/core/src/hooks/usePromiseTransaction.ts
packages/core/src/hooks/useSendTransaction.ts

Imports from `../../src` were causing problems in `jest`.

🗽 Use more specific imports

---

packages/core/src/hooks/estimateGasLimit.test.ts
packages/core/src/hooks/useContractFunction.ts
packages/core/src/hooks/usePromiseTransaction.ts
packages/core/src/hooks/useSendTransaction.ts

closes https://github.com/TrueFiEng/useDApp/issues/804
closes https://github.com/TrueFiEng/useDApp/issues/782

👨🏻‍🔧 Change estimating function in useContractCall

---

.changeset/change-switchNetwork-to-promise.md
packages/core/src/hooks/useEthers.ts

closes https://github.com/TrueFiEng/useDApp/issues/758
closes https://github.com/TrueFiEng/useDApp/issues/743

🕸 Change type declaration in swithNetwork

---

.changeset/change-switchNetwork-to-promise.md
packages/core/src/hooks/useContractFunction.test.tsx
packages/core/src/hooks/useContractFunction.ts
packages/core/src/hooks/useEthers.ts
packages/core/src/hooks/useSendTransaction.test.ts
packages/core/src/hooks/useSendTransaction.ts

closes https://github.com/TrueFiEng/useDApp/issues/757
closes https://github.com/TrueFiEng/useDApp/issues/720
closes https://github.com/TrueFiEng/useDApp/issues/714

😶‍🌫️ Add receipt and tests for contract function and transaction

---

.changeset/siwe-session-improvements.md
packages/siwe/src/provider.tsx
packages/siwe/src/requests.tsx

closes https://github.com/TrueFiEng/useDApp/issues/809

🐭 Add better siwe account holders and useCallbacks for functions

---

.changeset/only-metamask.md
packages/core/src/helpers/injectedProvider.ts
packages/core/src/providers/network/network/provider.tsx

closes https://github.com/TrueFiEng/useDApp/issues/724

🦊 Add provider filtering logic after activate browser wallet

---

.changeset/flat-windows-walk.md
packages/core/src/hooks/usePromiseTransaction.ts
packages/core/src/model/TransactionStatus.ts

🌵 Add error code to transaction status

---

.github/workflows/release.yml

💫 Update release with a new GH bot account

---

.changeset/fix-multicall-localhost-deployment.md
packages/core/package.json
packages/core/src/hooks/useLocalStorage.ts
packages/core/src/providers/DAppProvider.tsx
packages/core/src/providers/LocalMulticallProvider.tsx
pnpm-lock.yaml

closes https://github.com/TrueFiEng/useDApp/issues/440

🥗 Fix multiple deploying multicall during localhost connection

---

.changeset/gas-limit-percentage.md
packages/core/src/hooks/useContractFunction.test.tsx
packages/core/src/hooks/useContractFunction.ts
packages/core/src/hooks/useSendTransaction.test.ts
packages/core/src/hooks/useSendTransaction.ts
packages/core/src/model/TransactionOptions.ts
packages/docs/docs/02-Guides/03-Transactions/01-Ether Transactions.mdx
packages/docs/docs/02-Guides/03-Transactions/02-Contract Functions.mdx
packages/docs/src/examples/ContractFunction.tsx

closes https://github.com/TrueFiEng/useDApp/issues/713

😶‍🌫️ Add gas limiter to use contract function

---

packages/core/package.json
packages/core/tsconfig.json
packages/core/tsconfig.test.json

1. Open JavaScript Debug Terminal
2. Set breakpoints
3. `pnpm run test`

👨‍💻 Add test TS config to enable debugging

---

.changeset/fresh-days-give.md
packages/core/src/constants/type/Config.ts
packages/core/src/hooks/useContractFunction.test.tsx
packages/core/src/hooks/useContractFunction.ts
packages/core/src/hooks/usePromiseTransaction.ts
packages/core/src/hooks/useSendTransaction.test.ts
packages/core/src/hooks/useSendTransaction.ts
packages/core/src/model/TransactionOptions.ts
packages/core/src/providers/config/provider.tsx
packages/docs/docs/02-Guides/03-Transactions/01-Ether Transactions.mdx
packages/docs/docs/02-Guides/03-Transactions/02-Contract Functions.mdx
packages/docs/src/examples/ContractFunction.tsx
packages/docs/src/examples/SendTransaction.tsx

Sounds much better than `bufferGasLimitPercentage`.
Backwards compatibility is there.

⛽️ Introduce `gasLimitBufferPercentage` alias

---

.changeset/dirty-worms-walk.md
packages/core/src/hooks/useEthers.test.tsx
packages/core/src/hooks/useEthers.ts
packages/core/src/testing/renderWeb3Hook.tsx
packages/example/src/components/account/AccountButton.tsx
packages/example/src/components/account/Web3ModalButton.tsx
packages/example/src/components/account/Web3ReactConnectorButton.tsx

Closes https://github.com/TrueFiEng/useDApp/issues/533

♨️ Properly update error when switching to not configured network

---

packages/core/src/constants/type/Config.ts
packages/core/src/model/TransactionOptions.ts
packages/docs/docs/03-API Reference/03-Models.mdx

Progresses https://github.com/TrueFiEng/useDApp/issues/900

📃 Add missing doc about gasLimitBufferPercentage in TransactionOptions

---

packages/docs/docusaurus.config.js
packages/docs/package.json
pnpm-lock.yaml

Closes https://github.com/TrueFiEng/useDApp/issues/900

🔍 Add local search to docs

---

.changeset/tame-buttons-own.md
packages/core/.mocharc.json
packages/core/src/hooks/useCallResilency.test.tsx
packages/core/src/hooks/useEthers.test.tsx
packages/core/src/hooks/useEthers.ts

Closes https://github.com/TrueFiEng/useDApp/issues/913

👮‍♀️ Disable `chainId` in `useEthers` only on unsupported or not configured chains

---

packages/core/src/providers/network/readonlyNetworks/provider.tsx

Completes https://github.com/TrueFiEng/useDApp/pull/911 which still fails with WebsocketProvider

👉 Completes WebsocketProvider pollingInterval fixes

---

.changeset/lovely-taxis-dress.md
packages/core/src/model/chain/polygon.test.ts
packages/core/src/model/chain/polygon.ts

Closes https://github.com/TrueFiEng/useDApp/issues/945

🛺 Add Polygon/Mumbai `rpcUrl`

---

packages/docs/docs/02-Guides/01-Connecting/08-Wallet Connectors.mdx

Closes https://github.com/TrueFiEng/useDApp/issues/968

🥒 Add a version note for connector docs

---

.changeset/slow-numbers-joke.md
packages/core/src/model/chain/optimism.ts

Closes https://github.com/TrueFiEng/useDApp/issues/990

🍎 Add Optimism mainnet and testnets native currencies

---

.changeset/slow-numbers-joke.md
packages/core/src/helpers/getSignerFromOptions.ts
packages/core/src/hooks/useEthers.test.tsx
packages/core/src/hooks/useEthers.ts
packages/core/src/hooks/usePromiseTransaction.ts
packages/core/src/model/chain/optimism.ts
packages/core/src/providers/LocalMulticallProvider.tsx
packages/core/src/testing/connectContractToSigner.test.ts
packages/siwe/src/provider.tsx

Closes https://github.com/TrueFiEng/useDApp/issues/957

😼 Add FallbackProvider type for library in useEthers

---

packages/docs/docs/02-Guides/01-Connecting/08-Wallet Connectors.mdx

Should be `@usedapp/wallet-connect-connector`
https://www.npmjs.com/package/@usedapp/wallet-connect-connector

🤵‍♂️ Correct typo

---

.changeset/little-cheetahs-carry.md
packages/connectors/portis/src/index.ts
packages/connectors/wallet-connect/src/index.ts
packages/core/src/hooks/useEthers.test.tsx
packages/core/src/hooks/useEthers.ts
packages/core/src/providers/network/connectors/connectorController.ts
packages/core/src/providers/network/connectors/context.tsx
packages/core/src/providers/network/connectors/implementations/coinbase.ts
packages/core/src/providers/network/connectors/implementations/metamask.ts

⛄️ Return connector errors in useEthers

---

.changeset/five-bats-thank.md
packages/core/src/providers/window/provider.tsx

👁️ Visibility state check document for existence
