TrueFiEng/useDApp

docs/source/getting-started.rst
Example uses `readOnlyChain` when it should be `readOnlyChainId`
=> Update config example

docs/source/getting-started.rst
In order to explain how to connect with other connectors than browser wallets
=> Doc: Add activate method in getting-started

.changeset/lovely-jars-help.md, packages/core/src/providers/config/index.ts, packages/core/src/providers/index.ts
Isn't useConfig meant to be exposed according to the doc?
figured it isn't exported to the public except internally, at least according to Intellisense
=> Expose useConfig as public API

docs/source/getting-started.rst
In Core API hook is documented correctly, only there was an error.
=> Corrected useTokenBalance() arguments order

packages/core/package.json, packages/testing/package.json
minor fix to show the correct repo link in NPM https://www.npmjs.com/package/@usedapp/core (current link will redirect to the correct one though)
=> rename git repo link from dapp-framework to useDApp

docs/source/core.rst, packages/core/src/hooks/useEthers.ts
`activateBrowserWallet` in `useEthers` hook didn't have the proper typing for the function signature. The params `(onError?: (error: Error) => void, throwErrors?: boolean)` were missing.
Came here from 0xHack! 👋 Cheers!
=> Fix return type of `activateBrowserWallet`

.changeset/sweet-apes-accept.md, packages/core/src/hooks/useGasPrice.ts
Hi, I ran into some issues with newer versions of useDApp in my application when trying to install dependencies. Javascript/node is not my strength so I'm not 100% sure why it failed and why my fix works, hopefully this works for everyone. My guess is that the import was resolving to node installed packages instead of resolving to the current file in src
=> Fixed dependency issue when installing applications dependencies

docs/source/_static/custom.css
As of now it's hard to tell at a glance where one subject ends and where the other begins in docs. This PR is a proposition of improving readability. Opinions and propositions are welcome about how to improve it.
=> Improve docs readability 

packages/coingecko/README.md
Add coingecko package readme to display in npm package page https://www.npmjs.com/package/@usedapp/coingecko
refer from https://github.com/EthWorks/useDApp/blob/master/packages/core/README.md
the document is linked to https://usedapp.readthedocs.io/en/latest/coingecko.html
=> (coingecko) add readme

.changeset/modern-colts-knock.md, packages/core/src/providers/devtools.ts
Adds a check to see if `window` is defined, which prevents an error on Next.js due to server side rendering.
=> fix(devtools): Adding a check for window object

.changeset/light-walls-explode.md, packages/core/src/hooks/usePromiseTransaction.ts
Check for the existence of rpc error messages and use them, this prevents the mass "cannot estimate gas" messaging for errors that aren't related to gas.
Fixes https://github.com/EthWorks/useDApp/issues/260
=> feat: better error messaging

.changeset/chilly-timers-chew.md, .changeset/nice-buttons-sit.md, packages/core/src/hooks/useChainCalls.ts, packages/core/src/hooks/useContractFunction.ts, packages/core/src/hooks/usePromiseTransaction.ts
Fixes #280 causing certain hooks to update on any parent component re-render because return values were not being memoized in any way.
Passes all tests and confirmed it fixes the issues as far as I could see
=> Memoize hook return values to prevent unnecessary re-renders

.changeset/grumpy-items-wonder.md, packages/core/src/hooks/useLookupAddress.ts
Networks like matic don't have ens lookup and throw errors on the application when checking
=> Fix: handle lookupAddress errors

.changeset/seven-buckets-trade.md, packages/core/src/hooks/usePromiseTransaction.ts
Currently there is a bug with metamask which results in chainId in transaction being always 0.
https://github.com/MetaMask/metamask-extension/issues/11892
I don't yet know how should we handle it (it may changed after EIP-1559?)
=> Add workaround for current metamask chainId bug

.changeset/hip-weeks-prove.md, packages/core/src/hooks/usePromiseTransaction.ts
- Checks for `e.data.message` when a transaction fails, currently it just returns `Internal JSON-RPC error`
**Returned error example**
=> feat: improve errorMessage on transaction error

.changeset/eighty-worms-itch.md, packages/core/src/hooks/useContractFunction.ts
Avoid `No Matching event` by only calling `parseLog` on the logs that correspond to the current contract called.
I'm not sure if this is the best solution for the problem, ideally we should return the logs unparsed but that can be found in the transaction itself
=> feat: filter contract logs for events

docs/source/getting-started.rst
I found out how to import the `useEthersBalance` and the `useEthers` hooks from the [Balance.tsx](https://github.com/EthWorks/useDApp/blob/d2ce1ab9b608d8683f12d7ff2c2c17baaf7df2db/packages/example/src/pages/Balance.tsx) component in the example project.
=> docs: add missing imports in getting-started.rst

docs/source/getting-started.rst
I was slightly confused in the very first example about where "formatEther" was coming from :)
=> Add missing import for "formatEther" in example

.changeset/calm-weeks-move.md, packages/coingecko/src/simple_price.ts, packages/coingecko/src/simple_token_price.ts
Using the coingecko package currently breaks your app if you use a SSR framework like [Next.js](https://nextjs.org)
This PR is a simple fix to ensure that `window` doesn't get evaluated if it doesn't exist in the environment that the code is run in.
Use [isomorphic-fetch](https://www.npmjs.com/package/isomorphic-fetch) so that the price can be fetched both client-side and server-side? This would however introduce another dependency to the project.
=> Don't break SSR apps with Coingecko hook

.changeset/thin-peaches-travel.md, docs/source/core.rst, packages/core/src/model/config/Config.ts, packages/core/src/model/config/default.ts, packages/core/src/providers/transactions/provider.tsx
We had a problem that transactions field in local storage has already been used and feel like this could be a problem for others as well. 
It's easier to override useDapps LS path than to perform a local storage migration
=> Add transactions path in local storage to config

.changeset/four-snails-change.md, docs/source/core.rst, packages/core/src/hooks/usePromiseTransaction.ts, packages/core/src/model/TransactionStatus.ts, packages/core/src/providers/notifications/model.ts, packages/core/src/providers/transactions/model.ts
Currently if a user speeds up a transaction the old transaction will report as failed and the new one will not exist in useDapp state. This change adds some handling around the failed transaction to check if it was replaced and repriced and should therefore continue on as a new pending transaction.
Would really appreciate any feedback on this. We're currently using a similarly updated version of useContractFunction in prod on NFTX.
=> ↔️ Feat: handle dropped and replaced transactions

docs/source/core.rst
I think the former name is a mistake b/c I don't see it exported in the API. I can use `useLookupAddress()`
=> useDisplayName => useLookupAddress

docs/source/getting-started.rst
Adding the `Config` type to the `@usedapp/core` import within the Example section of Getting Started. 
It'd be nice if these Cmd + c lines were good to go :p
=> Added Config import to example code

.changeset/funny-wolves-learn.md, packages/core/src/hooks/useContractCall.ts
We had some nasty debugging when all useDapp calls stoped working after switching to Ropsten. Turns out, one of addresses was undefined for ropsten and all we got was Invalid ENS Name error in console. 
**Maybe we should also test if address has correct format to handle this better?**
=> 🦞 Skip multicall if address is undefined

docs/source/guide.rst
The previous example seems to be outdated.
=> Fix useTokenBalance custom hook example

.github/workflows/release.yml
> The workflow file using `changesets/action` is currently using `@master` as the version. This branch has been frozen and deprecated. Please update your workflow to either use `@v1` or a specific commit SHA that is tagged.
This change should fix this
=> 🤺 Fight the warning in Release action

.changeset/gentle-hairs-smoke.md, packages/core/src/providers/LocalMulticallProvider.tsx
due to `LocalMulticallProvider` still use the `isLocalChain` helper
isLocalChain warning is shown while run `yarn start` for the example
=> fix isLocalChain warning in local development

.changeset/smart-dragons-admire.md, .github/workflows/CI.yml, packages/coingecko/package.json, packages/core/package.json, packages/extension/package.json, packages/testing/package.json
Align with current LTS support
12, 14, 16 are LTS versions
https://nodejs.org/en/about/releases/
=> 🧿 update node matrix in CI

.changeset/dirty-worms-clean.md, docs/source/core.rst, packages/core/src/hooks/usePromiseTransaction.ts, packages/core/src/model/TransactionStatus.ts
* Add `PendingSignature` to TransactionState. (See the "Waiting on Signature..." disabled button in the screen shot. This PR makes this possible)
* Set `PendingSignature` state before each transaction begins so that errorMessages are reset on a new attempt
=> Add PendingSignature transaction state

.changeset/moody-candles-thank.md, docs/source/core.rst, docs/source/guide.rst, packages/core/src/hooks/useContractFunction.ts, packages/core/src/hooks/usePromiseTransaction.ts, packages/core/src/hooks/useSendTransaction.ts
* Return `resetState` in `usePromiseTransaction` so that it is easy to reset the view after a transaction.
* Return `resetState` in `useContractFunction`
* Return `resetState` in `useSendTransaction`
Currently there is no way to reset the UI after a user has submitted a transaction (that results in `Success`, `Fail`, or `Exception`). This PR makes it possible to call `resetState()` to reset the state to `None`. Let's say that as a developer we check for the `Success` status so we know we need to show a success React component. In this component we also have a "Mint More NFTs" button that we want to reset the status to `None` when clicked so that we can show the `MintNFTForm` React component. We can add `onClick={resetState}` to our button on the success React component and all of our …
=> Add resetState function for transactions

.changeset/violet-turkeys-sleep.md, packages/example/package.json
Currently `npm install` in the example package leads to a peer dependency conflict due to `react-refresh@^0.10.0,` in the package.json being specificed but `@pmmmwh/react-refresh-webpack-plugin@^0.4.3` requiring `react-refresh@">=0.8.3 <0.10.0"`. 
This fixes the example package.
=> Fix peer dependency conflict

packages/core/README.md
web3-react is no longer used in @useDapp/core as of v0.10.0, so thought perhaps it may be time to remove it.
=> chore(README): remove web3-react reference

packages/example/src/components/account/Web3ModalButton.tsx
Catches unhandled web3modal connection errors and places them into activation error position
Behaviour before handling the error:
https://user-images.githubusercontent.com/14224459/151959098-7ba79c2a-5f78-4271-9fa3-f0c7ac89855b.mp4
Behaviour after handling the error:
https://user-images.githubusercontent.com/14224459/151959128-0744c94a-2f1f-4dca-a688-52d2f6596074.mp4
This also works for other wallet connection options provided to web3modal (please ignore that I haven't set an image for the Coinbase wallet option):
https://user-images.githubusercontent.com/14224459/151959503-97809b16-5d58-4f32-ae23-d57cc1d481f4.mp4
=> fix(Web3ModalButton): catch web3modal connect errors

packages/core/.eslintrc.json, packages/core/package.json, yarn.lock
Official react hooks eslint plugin.
Found 26 new warnings that need to be addressed
=> 📝 Add eslint-plugin-react-hooks

.changeset/mighty-starfishes-stare.md, packages/core/.npmignore
Seems like sourcemaps were removed from published package in #496 and it causes issues (#521)
=> Add sourcemaps to build

packages/core/src/constants/type/Config.ts, packages/core/src/hooks/useEthers.ts, packages/core/src/hooks/useTokenList.ts, packages/core/src/model/Currency.ts, packages/core/src/model/TransactionStatus.ts, packages/core/src/providers/devtools.ts, packages/core/src/providers/network/model.ts, packages/core/src/providers/notifications/model.ts, packages/core/src/providers/notifications/reducer.ts, packages/core/src/providers/transactions/model.ts, packages/core/src/providers/transactions/reducer.ts
This PR removes the constraint that chainIDs be a member of the chainID enum. Instead, chainIDs are treated as type `number` in most situations.
Addresses https://github.com/EthWorks/useDApp/issues/482
=> 🧱 Add support for custom chainIDs

.eslintrc.json, packages/coingecko/.eslintrc.js, packages/coingecko/.eslintrc.json, packages/core/.eslintrc.js, packages/core/.eslintrc.json, packages/example/.eslintrc.js, packages/example/.eslintrc.json, packages/extension/.eslintrc.js, packages/extension/.eslintrc.json, packages/testing/.eslintrc.js, packages/testing/.eslintrc.json
When I CTRL+click into a definition of a useDApp type in VS Code, an ESLint plugin error pops up to say that it cannot resolve the eslint config at `../../.eslintrc.json`. 
This is because the eslint configs are not defined relative to the packages. This PR solves that.
=> 🔧 Fix ESLint relative directories

packages/core/src/hooks/useEthers.ts
In the documentation: 
```
networks List of intended supported chain configs. If a user tries to connect to an unsupported chain an error value will be returned by useEthers.
```
https://usedapp.readthedocs.io/en/latest/core.html?highlight=config#config
But in current version no `error` is returned.
So i added the code.
And it is consistent with the version before 0.9.1. When an `error` is returned, the chainId is returned as `undefined`.
=> 👮 If a user tries to connect to an unsupported chain an error value will be returned by useEthers.

packages/docs/docs/core.mdx
current version of useTransaction uses 'Fail' as tx status, instead of 'Failed'
=> 🔥 Updated useTransaction status values

packages/core/.npmignore
I previously thought I solved an issue with the VSCode ESLint plugin before with PR #568.
This however is actually the correct solution. There should be no need for the .eslintrc.js file to be in a published package.
=> 🔧 Add .eslintrc.js to .npmignore

.changeset/famous-badgers-wave.md, packages/core/src/hooks/useChainState.ts, packages/docs/docs/01-Getting Started/02-Reading.mdx, packages/docs/package.json, packages/docs/src/examples/GettingStarted.tsx, packages/docs/src/examples/ReadingWithoutWallet.tsx, packages/docs/src/examples/SendTransaction.tsx, packages/docs/src/examples/TokenBalance.tsx, pnpm-lock.yaml
- Fix a bug with read-only `chainId`
- Explicit `mainnet` default provider
- Example of read-only without browser wallet
=> 📙 Read-only example, without browser wallet

packages/core/src/hooks/useBlockMeta.ts, packages/core/src/hooks/useCall.ts, packages/core/src/hooks/useChainId.ts, packages/core/src/hooks/useChainState.ts, packages/core/src/hooks/useContractCall.ts
- Hook only for internal use, not exported
=> 🍜 Refactor: Extract `chainId` resolution to a hook

.changeset/green-keys-juggle.md, packages/core/src/providers/network/network/provider.tsx
I'm opening up a PR to potentially throw an error during a call to `activateBrowserWallet` if there is no injected provider detected.  This will allow for setting an error like so:
```
const [error, setError] = useState<string | undefined>(undefined)
...
<MyConnectionComponent
...rest of props
onClick={async () => {
try {
await activateBrowserWallet();
} catch (e) {
// handle if there is a message property, otherwise return raw message string
setError(e.message ?? e);
}
}}
/>
```
This will [match the flow later down in the function](https://github.com/TrueFiEng/useDApp/blob/master/packages/core/src/providers/network/network/provider.tsx#L52-L54) that throws if there is a failure during `eth_requestAccounts`.
I believe this would be an improvement over the current method of tracking an …
=> 👛 Add throw error to activateBrowserWallet

.github/workflows/deploy.yml
To avoid unnecessary deployments which do not contain any changes to review anyway.
Example: https://github.com/TrueFiEng/useDApp/pull/745
=> 👨‍🦼 Do not deploy apps on the release PR

.changeset/shaggy-dodos-sell.md, .github/workflows/CI.yml, packages/core/internal.d.ts, packages/core/internal.js, packages/core/package.json, packages/core/testing.d.ts, packages/core/testing.js, packages/siwe/package.json, packages/siwe/src/provider.test.tsx, packages/testing/src/index.ts, pnpm-lock.yaml
Removing submodules from `@usedapp/core` package because they were causing issues in older version of webpack and node.
=> 🥏 Remove submodules from core package

packages/core/src/hooks/usePromiseTransaction.ts
This changes check for `e.error?.data?.message` and help to specify error message when transaction fails.
Currently it returns `Internal JSON-RPC error`.
=> 👽 Update usePromiseTransaction.ts error message

.changeset/add-sctriter-check-useLogs.md, packages/core/src/hooks/useLogs.ts
Using generics in the **TypedFilter** interface add some nice type checks to the filter parameter of _useLogs_, but it doesn't help the user when creating the parameter, unless they go out of their way to instantiate he object with the _TypedFilter_ type specified. This way, the check is provided directly by the function. It can still be bypassed, if one wishes to, by calling it this way: 
```typescript
useLogs<Contract>(...)
```
I feel like this change could be applied to most hooks.
As a sidenote, I tried to make the output's value.data property typed, but I couldn't.
The best I could do was this, but it would work only if you could import *TypedEventFilter* from typechain's common file.
Maybe someone more skilled can work this out.
```typescript
type EventReturnTemp<T extends …
```
=> ➕ Add stricter contract type check on the useLogs hook

.changeset/hash-transaction-status.md, packages/core/src/hooks/usePromiseTransaction.ts, packages/core/src/model/TransactionStatus.ts
we can decode this hash and can be used to show error messages. This will be used mostly in custom error messages.
=> 🐸 Added error hash returned to transaction status

packages/core/src/hooks/useContractFunction.ts
**Description**
This fix adds opportunity to override gasLimit property when passing it to `send` method of useContractFunction hook.
It can be useful for troubleshooting and debugging failed transactions. Passing gasLimit helps to push transaction to the wallet even if transaction is going to fail.
=> ⛽ Fix gas limit override in useContractFunction hook

packages/website/src/index.html
The example code at [https://usedapp.io/#example](https://usedapp.io/#example) causes a type error due to a mis-named field. This PR fixes that. 
Note: The `readOnlyChain` field was renamed to `readOnlyChainId` as part of 8b8fb819b1cf7f71109ac025c52a1ed07df67569.
Related:
https://github.com/TrueFiEng/useDApp/blob/dfa48f552320cb771d7812e1d694960d4b581b69/packages/core/src/model/Config.ts#L12
https://github.com/TrueFiEng/useDApp/blob/8b8fb819b1cf7f71109ac025c52a1ed07df67569/packages/core/src/model/config/Config.ts#L12
=> 🌄 Fix field in website example code

packages/website/src/index.html
The `useTokenBalance()` hook in the website's example code references a deprecated hook, `useContractCall()`:
```ts
function useTokenBalance(
tokenAddress: string|Falsy,
address: string|Falsy): BigNumber|undefined
{
const [tokenBalance] = useContractCall (
address && tokenAddress && {
abi: ERC20Interface, // ABI interface of the called contract
address: tokenAddress, // On-chain address of the deployed contract
method: "balanceOf", // Method to be called
args: [address], // Method arguments - address to be checked for balance
}
) ?? [ ];
return tokenBalance;
}
```
https://github.com/TrueFiEng/useDApp/blob/master/packages/website/src/index.html#L336
This call yields a deprecation warning in editors like VS Code:
This PR updates the `useTokenBalance()` implementation to instead call …
=> 🪡 Fix example hook

.changeset/big-chairs-yell.md, packages/core/src/model/chain/xdai.ts
Add rpcUrl to gnosis chain  (former xdai) and close #934 
This enables the feature "add network" when gnosis chain in metamask isn't found.
=> 🦤 Add rpcUrl to xdai

.changeset/unlucky-countries-notice.md, packages/core/src/model/chain/bsc.ts
on BSC, the native token decimals is 18, while the decimals on BC is 8.
=> 🐶 Change BNB decimals on BSC from 8 to 18

.changeset/brave-planes-teach.md, packages/core/src/hooks/useBlockNumber.ts, packages/core/src/providers/blockNumber/blockNumbers/provider.tsx, packages/core/src/providers/chainState/multiChainStates/provider.tsx, packages/core/src/providers/network/readonlyNetworks/provider.tsx, packages/core/src/providers/window/context.ts, packages/core/src/providers/window/provider.tsx
Creating new object on every state change is probably not necessary here and just simple boolean can be returned.
=> 🪟 Simplify window provider

.changeset/spotty-cows-exist.md, packages/core/src/hooks/useContractFunction.ts
hi folks, thanks for your efforts being put into the framework, I enjoy using it for more than a year already. 🤝 
I noticed that in some of recent releases you've introduced  [gasLimitBufferPercentage](https://github.com/TrueFiEng/useDApp/pull/746) feature which is fine, but I just decided to push a small patch if it makes sense to you.
currently, on each `send` of `useContractFunction`  `estimateGas` is being called to modify transaction overrides with custom `gasLimit`. however, if `gasLimit` is passed explicitly in transaction overrides object, the value received by `estimateContractFunctionGasLimit` is being overwritten by it, and it appears that there was no point in calling `estimateContractFunctionGasLimit`.
this adds a check to skip calling `estimateContractFunctionGasLimit` if …
=> ⛽ Avoid calling estimateGas in useContractFunction when gasLimit is passed explicitly

.changeset/polite-ants-double.md, packages/core/src/hooks/usePromiseTransaction.ts
Closes https://github.com/TrueFiEng/useDApp/issues/1022
=> 🥐 Keep transactionName in notifications after the transaction is mined

.changeset/tame-knives-sneeze.md, packages/core/src/helpers/gnosisSafeUtils.ts, packages/core/src/hooks/useSendTransaction.ts
This format of non-empty data string is required on Gnosis Safe side.
=> 🧤 Add non-empty data string in Send Transaction

.changeset/tricky-spiders-cheer.md, packages/core/src/model/chain/optimism.ts
There's a double slash when calling `network.getExplorerTransactionLink(txHash)`
=> 🍆 Update optimism goerli etherscan link

.changeset/odd-weeks-dance.md, packages/core/src/hooks/useLookupAddress.ts
Add [Rave Names](https://rave.domains/) resolution into the `useLookupAddress` hook.
The hook will by default resolve to ENS, but if a second optional parameter is set to `true`, the hook will resolve to a Rave Name.
=> ➕ Add Rave Names resolution

.changeset/hip-pumpkins-play.md, packages/core/src/hooks/useLocalStorage.ts
1. Added `try catch` to prevent app crash because of `localStorage exceeded the quota` error. 
2. Added item remove from the local storage in `catch` to avoid `localStorage exceeded the quota` error on next setting.
The case when this error can occur:
- setting `transactions` to local storage, when transactions history exceeds storage limit.
=> 🛠️ Fix localStorage exceeded the quota error

.changeset/fluffy-houses-roll.md, packages/core/src/hooks/useContractFunction.ts
when estimateContractFunctionGasLimit throws an error,  the gasLimit should be null and the ethers contract will be checked again.
=> ⛽ Fix default gasLimit when estimateContractFunctionGasLimit throw error

packages/core/src/helpers/gnosisSafeUtils.ts
_WalletConnectV2_ incorrectly passes `safeTxGas` value, equal 0 (default value).
Thus we have a mismatch between gnosis `safeTxHash` and one calculated by _useDApp_ (`safeTxGas`is based on estimation).
This hot fix should be removed after _WalletConnectV2_ rectifies the problem.
=> ⛽ Settle safeTxGas

.changeset/adding_kroma.md, packages/core/src/constants/chainId.ts, packages/core/src/hooks/useConfig.test.tsx, packages/core/src/model/chain/kroma.ts
https://kroma.network/ all the data was captured from then.
it's relatively new chain, not even have verified contracts at kroma network blockscout.
=> 🐳 Add kroma network

.changeset/great-drinks-help.md, packages/core/src/model/chain/optimism.ts
Optimism Goerli testnet is really not in use these days and many rpc providers (like alchemy) don't even support it. So, thought of adding `Optimism Sepolia`. Really got to create my own `chain.ts` file for that particular testnet use. Well, now it be easy for others!
Got the information related to this testnet from these two links -> [Optimism Official site](https://chainid.link/?network=op-sepolia) and [Multicall Address for sepolia](https://github.com/mds1/multicall/blob/main/deployments.json)
Thanks
=> 🔴 Add Optimism Sepolia testnet

packages/coingecko/src/hooks/useCoingeckoTokenPrices.test.tsx
Coingecko allows fetching only 1 token per call now so it has to be changed in test
=> 💅 Update coingecko test
